### ISSUE TITLE
Make use of meta/argument_specs.yml if exists

### ISSUE THREAD

**Issue by adaemmer** [claranet/ansible-gendoc#11]
It would be nice if argument specification would be use. see https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-argument-validation

**Comment by stephrobert** [comment]
It's a very good idea ! Thanks

**Comment by stephrobert** [comment]
What do you thing about this ?  
  ### Default variables                                                                           
                                                                                                  
  #### main                                                                                       
                                                                                                  
  Install Memcached                                                                               
                                                                                                
      VARIABLE NAME   │      DESCRIPTION      │ TYPE │ ELEMENTS │ REQUIRED │ DEFAULT              
  ────────────────────┼───────────────────────┼──────┼──────────┼──────────┼──────────            
    memcached_verbose │ enable verbose in log │ bool │          │          │ True                 
    memcached_memory  │ test                  │ int  │          │          │      64              
    
 Have you roles to test ?

**Comment by adaemmer** [comment]
Looks good. I would prefer to have this order Variable name, Required, Type, Default, Description. With type for lists e.g. list(str).
All columns are relatively small so Description at the end could just grow.

If required is undefined it is false. You should print out false.

A good set of role to test could be https://github.com/ansible-middleware/wildfly
