### ISSUE TITLE
Minimal requirement of meta/main.yml

### ISSUE THREAD

**Issue by damienvergnaud** [claranet/ansible-gendoc#8]
Traceback returned by ansible-gendoc render without thoses key/values in meta/main.yml at least with default template in 1.0.6 version.

```
galaxy_info:
  namespace: namespace
  role_name: acmetool
```

Errors : 
```
KeyError: 'role_name'
Or 
KeyError: 'namespace'
```

Should we add minimal requirements in order for ansible-gendoc to proceed with the default template ? 
- Parse all the files and throw an error if minimal key:values aren't provided.
- Improve readme to explicit what's at least required for gendoc to render the role into doc.

**Comment by stephrobert** [comment]
Hi,

I used some roles from Claranet and in their meta/main.yml I found namespace/ After verification on Ansible Galaxy I replace it by Athor.

Fixed in 0.1.7

Thanks. See you soon
